### ISSUE TITLE
무비디비 파싱

### ISSUE THREAD

**Issue by Jhuni0123** [kalaluthien/DataStructure#2]
http://soar.snu.ac.kr/course/board/index.php?mid=ds2016&page=2&document_srl=1622394

제목이나 장르 좌우의 공백은 무시하도록 하여 out.txt 업데이트 해주세요

**Comment by kalaluthien** [comment]
심심할 때 무비디비를 다 짜서 새로운 out.txt를 만들도록 하겠습니다.
