### ISSUE TITLE
First testcase in "in1.txt" doesn't work (StackCalculator)

### ISSUE THREAD

**Issue by dnsdhrj** [kalaluthien/DataStructure#3]
in1.txt의 첫번째 테스트케이스가 무조건 ERROR를 띄웁니다
파일을 입력으로 넣으면 ERROR가 뜨고, 텍스트를 복사/붙여넣기하면 올바른 결과가 나옴.

+)테스트케이스를 수정하거나 추가해봐도 무조건 첫번째만 ERROR가 뜹니다.
아마 파일 인코딩 문제인듯(맨 처음에 이상한 문자가 있다거나)

**Comment by kalaluthien** [comment]
파일 인코딩 문제인 것 같아요.
어떤 환경에서 실행하셨나요?
저는 우분투 14.04에서 실행하였습니다.

**Comment by Jhuni0123** [comment]
저도 OS X 와 우분투에서 실행해봤는데 둘 모두 테케 파일로 돌리면 안되고 직접 입력하면 정상작동합니다.

**Comment by kalaluthien** [comment]
파일을 stdin으로 넣었나요?
무슨 문제지

**Comment by Jhuni0123** [comment]
잘 됩니다

**Comment by dnsdhrj** [comment]
22
