### ISSUE TITLE
[Subway] File encoding is not 'UTF-8' 

### ISSUE THREAD

**Issue by Jhuni0123** [kalaluthien/DataStructure#4]
파일 인코딩이 'euc-kr' 인 것 같아요
한글을 제대로 못읽어요
저의 자바 프로그램이 'UTF-8' 을 원해요.

**Comment by kalaluthien** [comment]
벌써 Subway를 하는 군요.
여기 있는 file은 원래 Windows에서 받아오는 바람에 그렇게 되어버렸을텐데
제가 Matching부터 만들고(?) 처리하도록 하겠습니다.

**Comment by kalaluthien** [comment]
처리 완료
